[package]
name = "collector"
version = "0.1.0"
authors = ["Robert Helmer <rhelmer@rhelmer.org>"]

[dependencies]
s3 = { path = "src/s3" }
hyper = "0.7.2"
log = "0.3.4"
log4rs = "0.3.3"
kafka = "0.1.8"
uuid = "0.1.18"
